config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :managers
  # devise_for :developers
  #
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  resources :users, only: %i[index show destroy] do
    resources :achievements, only: %i[index]
    resources :contracts, only: %i[index]
  end

  resources :achievements

  resources :attachments, only: %i[destroy]

  resources :comments, except: %i[show index] do
    resources :comments, shallow: true, except: %i[show index]
  end

  resources :contracts

  resources :notification_settings

  resources :projects

  resources :reports

  resources :tasks do
    resources :comments, shallow: true, except: %i[show index]
  end

  authenticate :user, -> (user) { user.admin? || user.manager? } do
    get '/auth/callback', to: 'slack#callback'
    get '/slack_token', to: 'pages#slack_token'
  end
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  include Commentable

  belongs_to :project
  belongs_to :user
  belongs_to :implementer, class_name: 'User'
  has_many_attached :files

  validates :title, presence: true, length: { minimum: 5 }, uniqueness: true
  validates :body, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true
  validates :status, presence: true

  delegate :title, to: :project, prefix: true, allow_nil: true

  validates_with DateValidator

  enum status: { open: 0, solved: 1, closed: 2 }
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :authorize_task, only: %i[index new create]

  def index
    @tasks = policy_scope(Task).paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @task = Task.new
  end

  def edit; end

  def create
    @task = Task.new(task_params.merge(user: current_user))

    if @task.save
      redirect_to task_url(@task)
    else
      render 'new'
    end
  end

  def update
    if @task.update(task_params)
      redirect_to task_url(@task)
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = authorize policy_scope(Task).find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :body, :start_time, :finish_time, :status, :project_id, :user_id,
                                 :implementer_id, files: [])
  end

  def authorize_task
    authorize Task
  end
end

app/views/tasks/_form.html.erb
<%= form_with model: model, local: true, class:'box' do |form| %>
  <%= render 'common/errors', resource: model %>

  <% if Project.all.empty? %>
    <p>In current time you can't create new task because we nave no projects</p>
  <% else %>
    <%= render 'common/select_project_section', builder: form %>

    <%= render 'common/select_user_section', builder: form, table_field: :implementer_id %>

    <div class="field">
      <%= form.label :title, class:'label' %>
      <div class="control">
        <%= form.text_field :title, class:'input' %>
      </div>
    </div>

    <div class="field">
      <%= form.label :body, class:'label' %>
      <div class="control">
        <%= form.text_area :body, class:'input' %>
      </div>
    </div>

    <div class="content">
      <%= render 'common/attachments', resource: model %>
      <%= render 'common/file_field_section', builder: form, field: :files %>
    </div>

    <div class="field">
      <%= form.label :start_time, class:'label' %>
      <div class="control">
        <%= form.date_field :start_time %>
      </div>
    </div>

    <div class="field">
      <%= form.label :finish_time, class:'label' %>
      <div class="control">
        <%= form.date_field :finish_time %>
      </div>
    </div>

    <div class="field">
      <%= form.label :status, class:'label' %>
      <div class="control">
        <div class="select">
          <%= form.select :status, Task.statuses.to_a.map { |w| [w[0].humanize, w[0]] } %>
        </div>
      </div>
    </div>

    <div class="field is-grouped">
      <div class="control">
        <%= form.submit model.new_record? ? t('tasks.submit.new') : t('tasks.submit.edit'), class:'button is-success' %>
      </div>
    </div>

  <% end %>

<% end %>

app/views/tasks/_task.html.erb
<tr>
  <td><%= task.title %></td>
  <td><%= task.body %></td>
  <td><%= task.start_time %></td>
  <td><%= task.finish_time %></td>
  <td><%= task.status %></td>
  <td><%= task.project_title %></td>
  <td><%= implementer_from_parent_instance(task) %></td>
  <td><%= task.files.size %></td>
  <td><%= link_to t('common.show_link'), task_path(task), class:'button is-info' %></td>
  <% if (policy(task).edit? && current_user == task.user) || current_user.admin? %>
    <td><%= link_to t('common.edit_link'), edit_task_path(task), class:'button is-warning' %></td>
    <td><%= link_to t('common.destroy_link'), task_path(task),
                    method: :delete,
                    data: { confirm: t('common.confirm') }, class:'delete is-large' %></td>
  <% end %>
</tr>

app/views/tasks/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', model: @task %>

<%= link_to t('common.back'), tasks_path, class:'button is-link' %>

app/views/tasks/index.html.erb
<%= render 'common/page_title', title: t('common.partials.tasks.header.listing') %>

<%= link_to t('.new_link'), new_task_path, class:'button is-link' %>

<% if @tasks.empty? %>
  <p><%= t('.empty') %></p>
<% else %>
  <table class="table is-fullwidth is-striped">
    <tr>
      <th><%= t('.title') %></th>
      <th><%= t('.body') %></th>
      <th><%= t('.start_time') %></th>
      <th><%= t('.finish_time') %></th>
      <th><%= t('.status') %></th>
      <th><%= t('.project') %></th>
      <th><%= t('.implementer') %></th>
      <th><%= t('.number_attachment') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <%= render partial: 'task', collection: @tasks, as: :task %>
  </table>
  <%= render 'common/paginate_component', objects: @tasks %>
<% end %>

app/views/tasks/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', model: @task %>

<%= link_to t('common.back'), tasks_path, class:'button is-link' %>

app/views/tasks/show.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <strong><%= t('.title') %>:</strong>
        <%= @task.title %>
      </div>
      <div class="content">
        <strong><%= t('.body') %>:</strong>
        <%= @task.body %>
      </div>
      <div class="content">
        <%= render 'common/attachments', resource: @task %>
      </div>
      <div class="content">
        <strong><%= t('.start_time') %>:</strong>
        <%= @task.start_time %>
      </div>
      <div class="content">
        <strong><%= t('.finish_time') %>:</strong>
        <%= @task.finish_time %>
      </div>
      <div class="content">
        <strong><%= t('.status') %>:</strong>
        <%= @task.status %>
      </div>
      <div class="content">
        <% if @task.project.nil? %>
          <p><%= t('.project_empty') %></p>
        <% else %>
          <strong><%= t('.project') %>:</strong>
          <%= @task.project_title %>
        <% end %>
      </div>
      <div class="content">
        <% if @task.user.nil? %>
          <p><%= t('.implementer_empty') %></p>
        <% else %>
          <strong><%= t('.implementer') %>:</strong>
          <%= implementer_from_parent_instance(@task) %>
        <% end %>
      </div>
    </div>
  </article>
</div>
<div id="comments-container" class="box">
  <p class="title is-4 has-text-centered"><%= t('.comments') %></p>
  <% if @task.comments %>
    <%= render partial: 'comments/comment', collection: @task.comments, as: :comment %>
  <% end %>
  <%= render 'comments/comment_form', resource: @task %>
</div>

<%= link_to t('common.back'), tasks_path, class:'button is-link' %>