config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :managers
  # devise_for :developers
  #
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  resources :users, only: %i[index show destroy] do
    resources :achievements, only: %i[index]
    resources :contracts, only: %i[index]
  end

  resources :achievements

  resources :attachments, only: %i[destroy]

  resources :comments, except: %i[show index] do
    resources :comments, shallow: true, except: %i[show index]
  end

  resources :contracts

  resources :notification_settings

  resources :projects

  resources :reports

  resources :tasks do
    resources :comments, shallow: true, except: %i[show index]
  end

  authenticate :user, -> (user) { user.admin? || user.manager? } do
    get '/auth/callback', to: 'slack#callback'
    get '/slack_token', to: 'pages#slack_token'
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :reports, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :contracts, dependent: :destroy
  has_many :implementers, through: :contracts, class_name: 'User', foreign_key: :implementer_id,
                          inverse_of: :implementer_projects
  has_many :slack_notification_settings, dependent: :destroy
  has_many_attached :files

  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { minimum: 5 }, uniqueness: true
  validates :body, presence: true
  validates :number_stages, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true
  validates :status, presence: true

  validates_with DateValidator

  enum status: { inactive: 0, active: 1, cancelled: 2, completed: 3 }

  scope :ordered_by_id, -> { order(id: :asc) }
  scope :implementer_or_author, lambda { |user|
                                  left_joins(:implementers)
                                    .where(contracts: { implementer_id: user.id })
                                    .or(left_joins(:implementers)
                                            .where(projects: { author_id: user.id }))
                                }
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authorize_project, only: %i[index new create]

  def index
    @projects = policy_scope(Project.ordered_by_id).paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params.merge(author: current_user))

    if @project.save
      redirect_to project_url(@project)
    else
      render 'new'
    end
  end

  def update
    if @project.update(project_params)
      redirect_to project_url(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy

    redirect_to projects_path
  end

  private

  def set_project
    @project = authorize policy_scope(Project).find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :body, :attachment, :number_stages,
                                    :start_time, :finish_time, :status, files: [])
  end

  def authorize_project
    authorize Project
  end
end

app/views/projects/_form.html.erb
<%= form_with model: model, local: true, class:'box' do |form| %>
  <%= render 'common/errors', resource: model %>

  <div class="field">
    <%= form.label :title, class:'label' %>
    <div class="control">
      <%= form.text_field :title, class:'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :body, class:'label' %>
    <div class="control">
      <%= form.text_area :body, class:'input' %>
    </div>
  </div>

  <div class="content">
    <%= render 'common/attachments', resource: model %>
    <%= render 'common/file_field_section', builder: form, field: :files %>
  </div>

  <div class="field">
    <%= form.label :number_stages, class:'label' %>
    <div class="control">
      <div class="select">
        <%= form.select(:number_stages) do %>
          <% (1..10).each do |c| -%>
            <%= content_tag(:option, c, value: c) %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :start_time, class:'label' %>
    <div class="control">
      <%= form.date_field :start_time %>
    </div>
  </div>

  <div class="field">
    <%= form.label :finish_time, class:'label' %>
    <div class="control">
      <%= form.date_field :finish_time %>
    </div>
  </div>

  <div class="field">
    <%= form.label :status, class:'label' %>
    <div class="control">
      <div class="select">
        <%= form.select :status, Project.statuses.to_a.map { |w| [w[0].humanize, w[0]] } %>
      </div>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= form.submit model.new_record? ? t('projects.submit.new') : t('projects.submit.edit'), class:'button is-success' %>
    </div>
  </div>

<% end %>

app/views/projects/_project.html.erb
<tr>
  <td><%= project.title %></td>
  <td><%= project.body %></td>
  <td><%= project.files.size %></td>
  <td><%= project.number_stages %></td>
  <td><%= project.start_time %></td>
  <td><%= project.finish_time %></td>
  <td><%= project.status %></td>
  <td><%= link_to t('common.show_link'), project_path(project), class:'button is-info' %></td>
  <% if (policy(project).edit? && current_user == project.author) || current_user.admin? %>
    <td><%= link_to t('common.edit_link'), edit_project_path(project), class:'button is-warning' %></td>
    <td><%= link_to t('common.destroy_link'), project_path(project),
                    method: :delete,
                    data: { confirm: t('common.confirm') }, class:'delete is-large' %></td>
  <% end %>
</tr>

app/views/projects/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', model: @project %>

<%= link_to t('common.back'), projects_path, class:'button is-link' %>

app/views/projects/index.html.erb
<%= render 'common/page_title', title: t('common.partials.projects.header.listing') %>

<%= link_to t('.new_link'), new_project_path, class:'button is-link' %>

<% if @projects.empty? %>
  <p><%= t('.empty') %></p>
<% else %>
  <table class="table is-fullwidth is-striped">
    <tr>
      <th><%= t('.title') %></th>
      <th><%= t('.body') %></th>
      <th><%= t('.number_attachments') %></th>
      <th><%= t('.number_stages') %></th>
      <th><%= t('.start_time') %></th>
      <th><%= t('.finish_time') %></th>
      <th><%= t('.status') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <%= render partial: 'project', collection: @projects, as: :project %>
  </table>
  <%= render 'common/paginate_component', objects: @projects %>
<% end %>

app/views/projects/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', model: @project %>

<%= link_to t('common.back'), projects_path, class:'button is-link' %>

app/views/projects/show.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <strong><%= t('.title') %>:</strong>
        <%= @project.title %>
      </div>
      <div class="content">
        <strong><%= t('.body') %>:</strong>
        <%= @project.body %>
      </div>
      <div class="content">
        <%= render 'common/attachments', resource: @project %>
      </div>
      <div class="content">
        <strong><%= t('.number_stages') %>:</strong>
        <%= @project.number_stages %>
      </div>
      <div class="content">
        <strong><%= t('.start_time') %>:</strong>
        <%= @project.start_time %>
      </div>
      <div class="content">
        <strong><%= t('.finish_time') %>:</strong>
        <%= @project.finish_time %>
      </div>
      <div class="content">
        <strong><%= t('.status') %>:</strong>
        <%= @project.status %>
      </div>
      <div class="content">
        <strong>Author:</strong>
        <%= @project.author.decorate.name_with_initial %>
      </div>
      <div class="content">
        <% if @project.tasks.empty? %>
          <p><%= t('.tasks_empty', title: @project.title) %></p>
        <% else %>
          <strong><%= t('.tasks') %>:</strong>
          <ul>
            <% @project.tasks.each do |task| %>
              <li><%=task.title %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <div class="content">
        <% if @project.reports.empty? %>
          <p><%= t('.reports_empty', title: @project.title) %></p>
        <% else %>
          <strong><%= t('.reports') %>:</strong>
          <ul>
            <% @project.reports.each do |report| %>
              <li><%=report.title %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <div class="content">
        <% if @project.implementers.empty? %>
          <p><%= t('.implementers_empty', title: @project.title) %></p>
        <% else %>
          <strong><%= t('.implementers') %>:</strong>
          <ul>
            <% @project.implementers.each do |implementer| %>
              <li><%=implementer.decorate.name_with_initial %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </article>
</div>

<%= link_to t('common.back'), projects_path, class:'button is-link' %>