config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :managers
  # devise_for :developers
  #
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  resources :users, only: %i[index show destroy] do
    resources :achievements, only: %i[index]
    resources :contracts, only: %i[index]
  end

  resources :achievements

  resources :attachments, only: %i[destroy]

  resources :comments, except: %i[show index] do
    resources :comments, shallow: true, except: %i[show index]
  end

  resources :contracts

  resources :notification_settings

  resources :projects

  resources :reports

  resources :tasks do
    resources :comments, shallow: true, except: %i[show index]
  end

  authenticate :user, -> (user) { user.admin? || user.manager? } do
    get '/auth/callback', to: 'slack#callback'
    get '/slack_token', to: 'pages#slack_token'
  end
end

app/views/common/_attachments.html.erb
<% if resource.files.attached? %>
  <strong><%= resource.files.size > 1 ? "#{t('common.attachment.many')}:" : "#{t('common.attachment.one')}:" %></strong>
  <ul>
    <%= render resource.files %>
  </ul>
<% elsif resource.persisted?%>
  <p><%= t('common.attachments_empty', title: resource.title) %></p>
<% end %>

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div class="message is-danger">
    <h2 class="message-header"><%= t('common.errors') %>:</h2>
    <div class="message-body">
      <ul>
        <% resource.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/common/_file_field_section.html.erb
<%= builder.label field, class:'label' %>
<div class="control">
  <%= builder.file_field field, multiple: true, class:'input' %>
</div>

app/views/common/_navbar.html.erb
<div class="container">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
    <%= link_to "Home page", root_path, class:'navbar-item' %>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
      <%if policy(current_user).index? %>
        <%= link_to 'Users', users_path, class:'navbar-item' %>
      <% end%>
      <% if policy(Contract).index? %>
        <%= link_to 'Contracts', contracts_path, class:'navbar-item' %>
      <% end %>
      <% if current_user.admin? || current_user.manager? %>
        <%= link_to 'Notification settings', notification_settings_path, class:'navbar-item' %>
        <%= link_to 'Get slack token', slack_token_path, class:'navbar-item' %>
      <% end %>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">More</a>

          <div class="navbar-dropdown">
            <%= link_to 'Achievements', achievements_path, class:'navbar-item' %>
            <%= link_to 'Projects', projects_path, class:'navbar-item' %>
            <%= link_to 'Reports', reports_path, class:'navbar-item' %>
            <%= link_to 'Tasks', tasks_path, class:'navbar-item'%>
          </div>
        </div>
      </div>

      <div class="navbar-end">
        <% if current_user %>
          <section class="media">
            <div class="media-left">
              <figure class="image is-60x60">
              <% if current_user.avatar.attached? %>
                <%= image_tag(current_user.avatar.variant(resize: "60x60!"), class:'is-rounded') %>
              <% else %>
                <%= user_gravatar(current_user, class:'navbar-avatar is-rounded') %>
              <% end %>
              </figure>
            </div>
            <div class="media-content">
              <div class="full-name has-icons-left">
                <span class="icon is-small is-left">
                  <%= fa_icon 'user' %>
                </span>
                <%= user_name_from_instance(current_user) %>
              </div>
              <div class="role has-icons-left has-text-weight-bold">
                <span class="icon is-small is-left">
                  <%= fa_icon 'tag' %>
                </span>
                <%= current_user.role %>
              </div>
              <div class="e-mail has-icons-left">
                <span class="icon is-small is-left">
                  <%= fa_icon 'envelope' %>
                </span>
                <%= current_user.email %>
              </div>
            </div>
          </section>
        <% end %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:'button is-primary' %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/common/_page_title.html.erb
<p class="title is-2 has-text-centered"><%= title %></p>

app/views/common/_paginate_component.erb
<%= will_paginate objects, renderer: BulmaPagination::Rails, class: 'is-centered' %>

app/views/common/_select_project_section.html.erb
<div class="field">
  <%= builder.label :project_id, 'Project', class:'label' %>
  <div class="control">
    <div class="select">
      <%= builder.collection_select :project_id, Projects::IndexValueObject.new(current_user).ordered_projects, :id, :title %>
    </div>
  </div>
</div>

app/views/common/_select_token_section.erb
<div class="field">
  <%= builder.label :integration_service_token_id, 'IntegrationServiceToken', class:'label' %>
  <div class="control">
    <div class="select">
      <%= builder.collection_select :integration_service_token_id, IntegrationServiceTokens::IndexValueObject.new(current_user).decorated_tokens, :id, :channel_with_workspace %>
    </div>
  </div>
</div>

app/views/common/_select_user_section.html.erb
<div class="field">
  <%= builder.label table_field, 'Implementer', class:'label' %>
  <div class="control">
    <div class="select">
      <%= builder.collection_select table_field, Users::IndexValueObject.new(current_user).decorated_users, :id, :full_name_with_postfix %>
    </div>
  </div>
</div>

app/views/common/_user_greetings_short_info.html.erb
<% if current_user.nil? %>
  <h1>Hello, someone</h1>
<% else %>
  <h1>Hello, <%= current_user.decorate.name_with_initial %> (<%= current_user.email %>)
    <strong><%= current_user.role.capitalize %></strong>
  </h1>
<% end %>

app/views/common/_user_profile.html.erb
<div class='columns'>
  <div class='container profile'>
    <div class='section profile-heading'>
      <div class='columns is-mobile is-multiline'>
        <div class='column is-2'>
          <span class='header-icon user-profile-image'>
            <% if current_user.avatar.attached? %>
              <%= image_tag(current_user.avatar) %>
            <% else %>
              <%= user_gravatar current_user %>
            <% end %>
          </span>
        </div>
        <div class='column is-4-tablet is-10-mobile name'>
          <p>
            <span class='title is-bold'>
              <%= current_user.first_name %>
              <%= current_user.patronymic %>
              <%= current_user.last_name %>
            </span>
            <%= link_to t('common.edit_link'), edit_user_registration_path(current_user), class:'button is-primary is-outlined' %>
          </p>
        </div>
        <div class="columns">
          <a class='column is-four-fifths is-4-mobile has-text-centered' href="<%= user_achievements_path(current_user) %>">
            <p class='stat-val'><%= current_user.achievements.size %></p>
            <p class='stat-key'>achievements</p>
          </a>
          <div class='column is-four-fifths is-4-mobile has-text-centered'>
            <p class='stat-val'><%= user_projects_size(current_user) %></p>
            <p class='stat-key'>projects</p>
          </div>
          <div class='column is-four-fifths is-4-mobile has-text-centered'>
            <p class='stat-val'><%= user_contracts_size(current_user) %></p>
            <p class='stat-key'>contracts</p>
          </div>
        </div>
      </div>
    </div>
    <div class='profile-options is-fullwidth'>
      <% if current_user.achievements.present? %>
        <%= render 'common/achievements/achievements_container' %>
      <% else %>
        <article class="message is-warning">
          <div class="message-header">
            <p>Warning</p>
          </div>
          <div class="message-body has-text-centered">
            You have no achievements
          </div>
        </article>
      <% end %>
      <% if current_user.own_projects.present? %>
        <p class="subtitle is-5 has-text-centered">Own projects</p>
        <%= render 'common/projects/projects_container', user_role: 'own', projects: current_user.own_projects  %>
      <% else %>
        <article class="message is-warning">
          <div class="message-header">
            <p>Warning</p>
          </div>
          <div class="message-body has-text-centered">
            You have no own projects
          </div>
        </article>
      <% end %>
      <% if current_user.implementer_projects.present? %>
        <p class="subtitle is-5 has-text-centered">Projects as implementer</p>
        <%= render 'common/projects/projects_container', user_role: 'implementer', projects: current_user.implementer_projects %>
      <% else %>
        <article class="message is-warning">
          <div class="message-header">
            <p>Warning</p>
          </div>
          <div class="message-body has-text-centered">
            You have no projects as implementer
          </div>
        </article>
      <% end %>
    </div>
  </div>
</div>