config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :managers
  # devise_for :developers
  #
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  resources :users, only: %i[index show destroy] do
    resources :achievements, only: %i[index]
    resources :contracts, only: %i[index]
  end

  resources :achievements

  resources :attachments, only: %i[destroy]

  resources :comments, except: %i[show index] do
    resources :comments, shallow: true, except: %i[show index]
  end

  resources :contracts

  resources :notification_settings

  resources :projects

  resources :reports

  resources :tasks do
    resources :comments, shallow: true, except: %i[show index]
  end

  authenticate :user, -> (user) { user.admin? || user.manager? } do
    get '/auth/callback', to: 'slack#callback'
    get '/slack_token', to: 'pages#slack_token'
  end
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_many_attached :files

  validates :title, presence: true, length: { minimum: 5 }, uniqueness: { scope: :user_id }
  validates :body, presence: true
  validates :amount_time, presence: true

  delegate :title, :finish_time, :author, :slack_notification_settings, to: :project, prefix: true, allow_nil: true
  delegate :url_helpers, to: 'Rails.application.routes'

  validates_with AssociativeProjectDateValidator

  def structure_for_slack
    { user: user.decorate.name_with_initial,
      title: title,
      body: body,
      amount_time: amount_time,
      project: "<#{url_helpers.project_url(project)}|#{project_title}>",
      project_deadline_date: ConvertTimeService.time_to_str_us(project_finish_time) }
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy]
  before_action :authorize_report, only: %i[index new create]

  def index
    @reports = policy_scope(Report.paginate(page: params[:page], per_page: 5))
  end

  def show; end

  def new
    @report = Report.new
  end

  def edit; end

  def create
    @report = Report.new(report_params.merge(user: current_user))

    if @report.save
      redirect_to report_url(@report)
      send_notification_about_report(@report)
    else
      render 'new'
    end
  end

  def update
    if @report.update(report_params)
      redirect_to report_url(@report)
    else
      render 'edit'
    end
  end

  def destroy
    @report.destroy

    redirect_to reports_path
  end

  private

  def set_report
    @report = authorize policy_scope(Report).find(params[:id])
  end

  def report_params
    params.require(:report).permit(:title, :body, :amount_time, :attachment,
                                   :project_id, :user_id, files: [])
  end

  def authorize_report
    authorize Report
  end

  def report_files(report)
    return unless report.files.attached?

    hash_to_merge = Hash.new([])
    report.files.each_with_index do |file, index|
      hash_to_merge["Attachment #{index + 1}"] = "<#{polymorphic_url(file)}|#{file.filename}>"
    end
    hash_to_merge
  end

  def report_data(report)
    report.structure_for_slack.merge(report_files(report).to_h)
  end

  def send_notification_about_report(report)
    report.project_slack_notification_settings.each do |slack_notification|
      webhook_url = EncryptionService.decrypt(slack_notification.token_properties[:webhook_url])
      SendSlackNotificationJob.perform_later(webhook_url, report_data(report))
    end
  end
end

app/views/reports/_form.html.erb
<%= form_with model: model, local: true, class:'box' do |form| %>
  <%= render 'common/errors', resource: model %>

  <% if Project.all.empty? %>
    <p><%= t('reports.projects_empty') %></p>
  <% else %>
    <%= render 'common/select_project_section', builder: form %>

    <div class="field">
      <%= form.label :title, class:'label' %>
      <div class="control">
        <%= form.text_field :title, class:'input', value: Faker::Lorem.sentence(word_count: 3) %>
      </div>
    </div>

    <div class="field">
      <%= form.label :body, class:'label' %>
      <div class="control">
        <%= form.text_area :body, class:'input', value: Faker::Lorem.sentence(word_count: 15) %>
      </div>
    </div>

    <div class="field">
      <%= form.label :amount_time, class:'label' %>
      <div class="control">
        <%= form.number_field(:amount_time, in: 1..999, step: 1) %>
      </div>
    </div>

    <div class="content">
      <%= render 'common/attachments', resource: model %>
      <%= render 'common/file_field_section', builder: form, field: :files %>
    </div>

    <div class="field is-grouped">
      <div class="control">
        <%= form.submit model.new_record? ? t('reports.submit.new') : t('reports.submit.edit'), class:'button is-success' %>
      </div>
    </div>

  <% end %>

<% end %>

app/views/reports/_report.html.erb
<tr>
  <td><%= report.title %></td>
  <td><%= report.body %></td>
  <td><%= report.files.size %></td>
  <td><%= report.amount_time %></td>
  <td><%= report.project_title %></td>
  <td><%= link_to t('common.show_link'), report_path(report), class:'button is-info' %></td>
  <% if policy(report).update? %>
    <td><%= link_to t('common.edit_link'), edit_report_path(report), class:'button is-warning' %></td>
  <% end %>
  <% if policy(report).destroy? %>
    <td><%= link_to t('common.destroy_link'), report_path(report),
                    method: :delete,
                    data: { confirm: t('common.confirm') }, class:'delete is-large' %></td>
  <% end %>
</tr>

app/views/reports/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', model: @report %>

<%= link_to t('common.back'), reports_path, class:'button is-link' %>

app/views/reports/index.html.erb
<%= render 'common/page_title', title: t('common.partials.reports.header.listing') %>

<%= link_to t('.new_link'), new_report_path, class:'button is-link' %>

<% if @reports.empty? %>
  <p><%= t('.empty') %></p>
<% else %>
  <table class="table is-fullwidth is-striped">
    <tr>
      <th><%= t('.title') %></th>
      <th><%= t('.body') %></th>
      <th><%= t('.number_attachments') %></th>
      <th><%= t('.amount_time') %></th>
      <th><%= t('.project') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <%= render @reports %>
  </table>
  <%= render 'common/paginate_component', objects: @reports %>
<% end %>

app/views/reports/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', model: @report %>

<%= link_to t('common.back'), reports_path, class:'button is-link' %>

app/views/reports/show.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <strong><%= t('.title') %>:</strong>
        <%= @report.title %>
      </div>
      <div class="content">
        <strong><%= t('.body') %>:</strong>
        <%= @report.body %>
      </div>
      <div class="content">
        <strong><%= t('.amount_time') %>:</strong>
        <%= @report.amount_time %>
      </div>
      <div class="content">
        <%= render 'common/attachments', resource: @report %>
      </div>
      <div class="content">
        <% if @report.project.nil? %>
          <p><%= t('.project_empty', title: @report.title) %></p>
        <% else %>
          <strong><%= t('.project') %>:</strong>
          <%= @report.project_title %>
        <% end %>
      </div>
    </div>
  </article>
</div>

<%= link_to t('common.back'), reports_path, class:'button is-link' %>